#!/bin/zsh
# Run with 'zsh'

# Change the install location if necessary:
prefix=/usr/local

#{{{ Functions

die() {
	>&2 echo "\n$*!"
	exit 1
}

diecmd() {
	>&2 echo "\nCommand not found: $1"
	>&2 echo "Open a new shell and run this script again to continue with the setup."
	exit 127
}

warn() {
	>&2 echo "\n$*!\n"
}

exist() {
	command -v $1 > /dev/null
}

islocal() {
	exist $1 && test "$(which $1)" != "/usr/bin/$1"
}

poured() {
	test -d "$prefix/Cellar/$1"
}

tapped() {
	test -d "$prefix/Library/Taps/$1"
}

inlibs() {
	test -e "/Library/$1" || test -e "$HOME/Library/$1"
}

inapps() {
	test -d "/Applications/$1.app" || test -d "$HOME/Applications/$1.app"
}

inhome() {
	test -e "$HOME/$1"
}

intmp() {
	test -f "$TMPDIR/$1"
}

#}}}

#{{{ Environment variables

setup=$(dirname "$0")
cfg="$HOME/.config/dotfiles"

echo "PATH = $PATH"
[ ${PATH#*$prefix/bin} = $PATH ] && export PATH="$prefix/bin:$PATH"
export TMPDIR=${TMPDIR:-/private/tmp}
export RBENV_ROOT="$prefix/rbenv"
export PYENV_ROOT="$prefix/pyenv"
export NVM_DIR="$prefix/nvm"
export PERLBREW_ROOT="$prefix/perlbrew"

#}}}

#{{{ Dotfiles

inhome .config/git || mkdir -p "$HOME/.config/git"
inhome .vim || mkdir "$HOME/.vim"
if ! inhome .config/dotfiles && ! inhome .localenv; then
	url="https://github.com/vbwx/dotfiles.git"
	git clone $url "$cfg" || warn "Can't clone $url"

	if [ -d "$cfg" ]; then
		inhome .bash_profile      || ln -s "$cfg/bash_profile" "$HOME/.bash_profile"
		inhome .bashrc            || ln -s "$cfg/bashrc" "$HOME/.bashrc"
		inhome .coffeelint.json   || ln -s "$cfg/coffeelint.json" "$HOME/.coffeelint.json"
		inhome .eslintrc.json     || ln -s "$cfg/eslintrc.json" "$HOME/.eslintrc.json"
		inhome .config/git/config || ln -s "$cfg/gitconfig" "$HOME/.config/git/config"
		inhome .config/git/ignore || ln -s "$cfg/gitignore" "$HOME/.config/git/ignore"
		inhome .vim/vimrc         || ln -s "$cfg/vimrc" "$HOME/.vim/vimrc"
		inhome .vim/gvimrc        || ln -s "$cfg/gvimrc" "$HOME/.vim/gvimrc"
		inhome .profile           || ln -s "$cfg/profile" "$HOME/.profile"
		inhome .scss-lint.yml     || ln -s "$cfg/scss-lint.yml" "$HOME/.scss-lint.yml"
		inhome .tern-project      || ln -s "$cfg/tern-project.json" "$HOME/.tern-project"
		inhome .localenv          || ln -s "$cfg/localenv" "$HOME/.localenv"
	fi
fi

#}}}

#{{{ Xcode

exist xcode-select || diecmd xcode-select
exist xcodebuild   || xcode-select --install

#}}}

#{{{ Homebrew

if ! exist brew; then
	url="https://raw.githubusercontent.com/Homebrew/install/master/install"
	curl -fsSLo "$TMPDIR/homebrew.rb" $url || warn "Can't download $url"
	intmp homebrew.rb && /usr/bin/ruby "$TMPDIR/homebrew.rb" || die "Can't install Homebrew"
fi
exist brew || diecmd brew

tapped caskroom || brew tap caskroom/cask

brew update

#{{{ Packages

exist ag               || brew install the_silver_searcher
exist automake         || brew install automake
poured bash-completion || brew install bash-completion
exist cmake            || brew install cmake
poured coreutils       || brew install coreutils
exist cowsay           || brew install cowsay
exist cscope           || brew install cscope
islocal ctags          || brew install ctags
exist fdupes           || brew install fdupes
exist ffmpeg           || brew install ffmpeg
exist fortune          || brew install fortune
exist fzf              || brew install fzf
islocal git            || brew install git
exist git-flow         || brew install git-flow
islocal gzip           || brew install homebrew/dupes/gzip
islocal less           || brew install homebrew/dupes/less
poured libtool         || brew install libtool
poured libvo-aacenc    || brew install libvo-aacenc
poured libyaml         || brew install libyaml
exist lua              || brew install lua
poured msgpack         || brew install msgpack
islocal php            || brew install homebrew/php/php70
exist php-cs-fixer     || brew install homebrew/php/php-cs-fixer
exist pyenv            || brew install pyenv
exist rbenv            || brew install rbenv
poured readline        || brew install readline
exist rename           || brew install rename
islocal rsync          || brew install homebrew/dupes/rsync
islocal svn            || brew install subversion
exist tig              || brew install tig
exist tree             || brew install tree
exist wdiff            || brew install wdiff
exist xz               || brew install xz

#}}}

#{{{ Casks

inapps "AppCleaner"                          || brew cask install appcleaner
inapps "Dropbox"                             || brew cask install dropbox
inapps "Firefox"                             || brew cask install firefox
inapps "GitHub Desktop"                      || brew cask install github-desktop
inapps "Google Chrome"                       || brew cask install google-chrome
inapps "HandBrake"                           || brew cask install handbrake
inapps "MacVim"                              || brew cask install macvim
inapps "MAMP/MAMP"                           || brew cask install mamp
inapps "OpenOffice"                          || brew cask install openoffice
inapps "Opera"                               || brew cask install opera
inapps "Platypus"                            || brew cask install platypus
inapps "Skim"                                || brew cask install skim
inapps "Skype"                               || brew cask install skype
inapps "Slack"                               || brew cask install slack
inapps "Suspicious Package"                  || brew cask install suspicious-package
inapps "TeamViewer"                          || brew cask install teamviewer
inapps "Things"                              || brew cask install things
inapps "Transmission"                        || brew cask install transmission
inapps "Transmit"                            || brew cask install transmit
inapps "VirtualBox"                          || brew cask install virtualbox
inapps "VLC"                                 || brew cask install vlc
inlibs "TeX"                                 || brew cask install mactex
inlibs "PreferencePanes/JavaControlPanel.prefPane" || brew cask install java
inlibs "QuickLook/BetterZipQL.qlgenerator"   || brew cask install betterzipql
inlibs "QuickLook/QLColorCode.qlgenerator"   || brew cask install qlcolorcode
inlibs "QuickLook/QLMarkdown.qlgenerator"    || brew cask install qlmarkdown
inlibs "QuickLook/QuickLookCSV.qlgenerator"  || brew cask install quicklook-csv
inlibs "QuickLook/QuickLookJSON.qlgenerator" || brew cask install quicklook-json
inlibs "QuickLook/WebP.qlgenerator"          || brew cask install webpquicklook

#}}}
#}}}

# TODO Install other macOS utilities

#{{{ Download shared files

if [ ! -d $prefix/share/unicode ]; then
	url="http://www.unicode.org/Public/UNIDATA/UnicodeData.txt"
	curl -fsSLo "$prefix/share/unicode/UnicodeData.txt" $url || warn "Can't download $url"
fi

#}}}

#{{{ Node.js

if [ -f "$NVM_DIR/nvm.sh" ]; then
	source "$NVM_DIR/nvm.sh"
else
	git clone https://github.com/creationix/nvm.git $NVM_DIR && (
		cd $NVM_DIR
		git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
	)
fi
exist nvm || diecmd nvm

if ! islocal node; then
	nvm install node || die "Can't install Node"
	nvm use node && nvm alias default node
fi
[ -e $prefix/node ] || ln -s "$NVM_DIR/versions/node/$(nvm current)" $prefix/node || warn "Can't symlink $prefix/node"

#{{{ Packages

exist npm                || diecmd npm
exist bower              || npm install -g bower
exist coffee             || npm install -g coffee-script
exist coffeelint         || npm install -g coffeelint
exist commitizen         || npm install -g commitizen
exist eslint             || npm install -g eslint
exist grunt              || npm install -g grunt-cli
exist gulp               || npm install -g gulp
exist instant-markdown-d || npm install -g instant-markdown-d
exist js-beautify        || npm install -g js-beautify
exist jsctags            || npm install -g jsctags
exist marked             || npm install -g marked
exist tsc                || npm install -g typescript
exist yo                 || npm install -g yo

#}}}
#}}}

#{{{ Ruby

exist rbenv || diecmd rbenv
eval "$(rbenv init -)"

if ! islocal ruby; then
	ver=$(rbenv install --list | sort -nr | perl -ne 'next unless /^\s*\d+\.\d+(\.\d+)?\n$/; s/\s//g; print; exit;')
	[ $ver ] || die "Can't fetch latest Ruby version"
	rbenv install $ver || die "Can't install Ruby"
	rbenv global $ver
fi

#{{{ Gems

exist gem       || diecmd gem
islocal gem     || die "rbenv doesn't seem to be active"
exist compass   || gem install -N compass
exist sass      || gem install -N sass sass-globbing
exist scss-lint || gem install -N scss_lint

#}}}
#}}}

#{{{ Perl

if ! exist perlbrew; then
	url="https://install.perlbrew.pl"
	curl -fLo "$TMPDIR/perlbrew.sh" $url || warn "Can't download $url"
	intmp perlbrew.sh && bash "$TMPDIR/perlbrew.sh" || die "Can't install Perlbrew"
fi
exist perlbrew || diecmd perlbrew
source "$PERLBREW_ROOT/etc/bashrc"

if ! islocal perl; then
	perlbrew install -n stable || die "Can't install Perl"
	ver=$(perlbrew list | perl -ne '/perl-[\d.]+/; print $&; $& and exit;')
	[ $ver ] || die "Can't find out installed Perl version"
	perlbrew alias create perl-$ver default && perlbrew switch default
fi

#{{{ Modules

exist cpan   || diecmd cpan
islocal cpan || die "perlbrew doesn't seem to be active"

#}}}
#}}}

#{{{ Python

exist pyenv || diecmd pyenv
eval "$(pyenv init -)"

if ! islocal python; then
	ver=$(pyenv install --list | sort -nr | perl -ne 'next unless /^\s*\d+\.\d+(\.\d+)?\n$/; s/\s//g; print; exit;')
	[ $ver ] || die "Can't fetch latest Python version"
	CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $ver || die "Can't install Python"
	pyenv global $ver
fi

#}}}

#{{{ PHP

if ! exist composer; then
	url="https://getcomposer.org/installer"
	curl -fLo "$TMPDIR/composer.php" $url || warn "Can't download $url"
	intmp composer.php && php "$TMPDIR/composer.php" --install-dir=$prefix/bin --filename=composer || die "Can't install Composer"
fi

#}}}

#{{{ Vim

[ -f "mvim" ] || die "Can't find mvim script"
link=$(readlink -n $prefix/bin/mvim)
[ "${link#*mvim}" = "$link" ] && cp -f mvim $prefix/bin

islocal vi       || ln -s $prefix/bin/mvim $prefix/bin/vi
islocal vim      || ln -s $prefix/bin/mvim $prefix/bin/vim
islocal gvim     || ln -s $prefix/bin/mvim $prefix/bin/gvim
islocal rvim     || ln -s $prefix/bin/mvim $prefix/bin/rvim
islocal rmvim    || ln -s $prefix/bin/mvim $prefix/bin/rmvim
islocal rgvim    || ln -s $prefix/bin/mvim $prefix/bin/rgvim
islocal view     || ln -s $prefix/bin/mvim $prefix/bin/view
islocal gview    || ln -s $prefix/bin/mvim $prefix/bin/gview
islocal mview    || ln -s $prefix/bin/mvim $prefix/bin/mview
islocal vimdiff  || ln -s $prefix/bin/mvim $prefix/bin/vimdiff
islocal gvimdiff || ln -s $prefix/bin/mvim $prefix/bin/gvimdiff
islocal mvimdiff || ln -s $prefix/bin/mvim $prefix/bin/mvimdiff
islocal viman    || ln -s $prefix/bin/mvim $prefix/bin/viman
islocal mviman   || ln -s $prefix/bin/mvim $prefix/bin/mviman
islocal gviman   || ln -s $prefix/bin/mvim $prefix/bin/gviman

islocal vim || diecmd mvim

if ! inhome .vim/spell/de.utf-8.spl; then
	url="http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl"
	curl -fsSLo --create-dirs "$HOME/.vim/spell/de.utf-8.spl"
fi
if ! inhome .vim/autoload/plug.vim; then
	url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
	curl -fsSLo --create-dirs "$HOME/.vim/autoload/plug.vim" $url || warn "Can't download $url"
fi
if ! inhome .vim/plugged; then
	vim -c PlugInstall -c q
fi

#}}}

#{{{ Prezto

if [ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ]; then
	git clone --recursive https://github.com/vbwx/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
	setopt EXTENDED_GLOB
	for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
		ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
	done
fi

echo "Shell = $SHELL"
[ $SHELL = "/bin/zsh" ] || chsh -s /bin/zsh
touch "$HOME/.hushlogin"

#}}}

#{{{ Set PATH for all apps

lpaths=(
	$prefix/bin
	$prefix/sbin
	$prefix/node/bin
	$prefix/perlbrew/perls/default/bin
	$prefix/pyenv/shims
	$prefix/rbenv/shims
	/Library/TeX/texbin
)
guipath=$(launchctl getenv PATH)
echo "GUI PATH = $guipath"

if [ "${guipath#*$prefix/bin}" = "$guipath" ]; then
	echo "New GUI PATH:"
	echo $(IFS=: ; echo "${lpaths[*]}"):$guipath
	sudo launchctl config user path "$(IFS=: ; echo "${lpaths[*]}"):$guipath"
fi
if [ $(head -n 1 /etc/paths) != "$prefix/bin" ]; then
	(IFS=$'\n'; echo "${lpaths[*]}" > "$TMPDIR/paths")
	cat /etc/paths >> "$TMPDIR/paths"
	if [ $(head -n 1 "$TMPDIR/paths") = "$prefix/bin" ]; then
		echo "New /etc/paths:"
		cat "$TMPDIR/paths"
		sudo mv -f "$TMPDIR/paths" /etc || die "Can't overwrite /etc/paths"
	else
		die "Can't create temporary paths file"
	fi
fi

#}}}

echo "All done."

# vim: fdm=marker:fdl=0:fdc=3
