#!/bin/bash

set +o histexpand -o errexit -o nounset -o pipefail -o noglob
shopt -s extglob

script="setup-env"
version=0.1
IFS=$'\n'
swd="$(dirname "$(readlink -f "$0")")"
args=("$@")

source "$swd/common/functions.bash"
load functions
load config common

[[ $# -eq 0 ]] && usage 1
[[ $1 == "--help" ]] && help
[[ $1 == "--version" ]] && println "$script $version" && exit

OPTIND=1
simulate=""
verbose=""

while getopts "sv" opt; do
	case $opt in
		(s) simulate=1;;
		(v) verbose=1;;
		(*) usage 1;;
	esac
done

shift $((OPTIND-1))
[[ $1 == '-' || $1 == '--' ]] && shift

for arg in "$@"; do
	if [[ -f "$arg.conf" ]]; then
		source "$arg.conf"
	else
		source "$arg"
	fi
done

isroot || rerun

for step in "${steps[@]}"; do
	println ">> $step"
	source "$swd/common/steps/$step.bash"
done

# Report failed installations

#if ! available download.virtualbox.org; then
#	echo "deb http://download.virtualbox.org/virtualbox/debian "$dist_ver" contrib" \
#		>> /etc/apt/sources.list.d/oracle.list
#	curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | apt-key add -
#	curl -fsSL https://www.virtualbox.org/download/oracle_vbox.asc | apt-key add -
#fi

# vim: fdm=marker:fdl=0:fdc=3
