#!/bin/bash

set +o histexpand -o errexit -o nounset -o pipefail -o noglob
shopt -s extglob

IFS=$'\n'
script="setup-env"
version=0.1
cwd="$(dirname "$(readlink -f "$0")")"
args=("$@")

source "$cwd/common/functions.bash"

platform="$(uname)"
platform="${platform,,}"
dist=""
desktop=""
if [[ $platform == "linux" ]]; then
	if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
		dist="$(lsb_release -i | cut -d: -f2 | sed 's/^\t//')"
	else
		set +f
		dist="$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v lsb | cut -d/ -f3 | cut -d- -f1 | cut -d_ -f1)"
		set -f
	fi
	distsetup="$(dirname "$0")/$dist"
	desktop="$DESKTOP_SESSION"
	mapval desktop
elif [[ $platform == *bsd ]]; then
	dist="$platform"
	platform=bsd
	desktop="$DESKTOP_SESSION"
fi

load functions
load config common

[[ $# -eq 0 ]] && usage 1
[[ $1 == "--help" ]] && help
[[ $1 == "--version" ]] && println "$script $version" && exit

OPTIND=1
simulate=""
verbose=""

while getopts "sv" opt; do
	case $opt in
		(s) simulate=1;;
		(v) verbose=1;;
		(*) usage 1;;
	esac
done

shift $((OPTIND-1))
[[ $1 == '-' || $1 == '--' ]] && shift

for arg in "$@"; do
	if [[ -f "$arg.conf" ]]; then
		source "$arg.conf"
	else
		source "$arg"
	fi
done

[[ ${PATH#*$prefix/bin} = "$PATH" ]] && PATH="$prefix/bin:$PATH"

isroot || rerun

#if ! available download.virtualbox.org; then
#	echo "deb http://download.virtualbox.org/virtualbox/debian "$dist_ver" contrib" \
#		>> /etc/apt/sources.list.d/oracle.list
#	curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | apt-key add -
#	curl -fsSL https://www.virtualbox.org/download/oracle_vbox.asc | apt-key add -
#fi

#}}}

# vim: fdm=marker:fdl=0:fdc=3
