#!/bin/bash

set -euo pipefail

targets=(
	appcache
	iconcache
	spotlight
)

function help {
	cat << END
NAME
	rebuild

SYNOPSIS
	rebuild target_name ...
	rebuild help

DESCRIPTION
	This utility provides a simple interface to rebuild caches and databases.

TARGETS
END
	listtargets
	exit $*
}

function listtargets {
	echo "\tall"
	for t in ${targets[*]}
		echo "\t$t"
}

if [ $# -eq 0 ]; then
	>&2 echo "What do you want to rebuild?"
	listtargets
	exit 1
fi

for t in $*; do
	case $t in
		all)
			$0 ${targets[*]}
			;;
		iconcache)
			sudo find /private/var/folders -name com.apple.dock.iconcache -exec rm {} \;
			sudo find /private/var/folders -name com.apple.iconservices -exec rm -rf {} \;
			sudo rm -rf /Library/Caches/com.apple.iconservices.store
			;;
		appcache)
			cd /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support
			./lsregister -kill -r -domain local-domain system -domain user -seed
			;;
		spotlight)
			sudo mdutil -E /
			;;
		help|--help)
			help
			;;
		*)
			alt=($(which -a rebuild))
			if [ ${#alt[@]} -gt 1 ]; then
				${alt[1]} "$@"
			else
				>&2 echo -e "Unknown target: $t\n"
				help 1
			fi
	esac
done
