#!/bin/bash

set -euo pipefail

targets=(
	apt
	cpan
	gem
	npm
	nvm
	pip
	prezto
	vim-plug
)

function help {
	cat << END
NAME
	update

SYNOPSIS
	update target_name ...
	update help

DESCRIPTION
	This utility provides a simple interface to perform updates of programs and packages.

TARGETS
END
	listtargets
	exit $*
}

function listtargets {
	echo -e "\tall"
	for t in ${targets[*]}; do
		echo -e "\t$t"
	done
}

if [ $# -eq 0 ]; then
	>&2 echo "What do you want to update?"
	listtargets
	exit 1
fi

for t in $*; do
	case $t in
		all)
			$0 ${targets[*]}
			;;
		apt)
			apt update
			apt dist-upgrade
			apt autoremove
			apt autoclean
			;;
		prezto)
			cd "${ZDOTDIR:-$HOME}/.zprezto"
			git pull
			git submodule update --init --recursive
			;;
		nvm)
			cd "$NVM_DIR"
			git fetch origin
			git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
			source "$NVM_DIR/nvm.sh"
			;;
		npm)
			npm install -g npm@latest
			npm update -g
			;;
		cpan)
			cpan -u
			;;
		pip)
			pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
			;;
		gem)
			gem update
			;;
		vim-plug)
			vim +PlugUpgrade +PlugUpdate +qall
			;;
		help)
			help
			;;
		*)
			alt=($(which -a update))
			if [ ${#alt[@]} -gt 1 ]; then
				${alt[1]} "$@"
			else
				>&2 echo -e "Unknown target: $t\n"
				help 1
			fi
	esac
done
