#!/bin/bash

set -euo pipefail

targets=(
	apt
	cpan
	gem
	npm
	nvm
	pip
	prezto
	texlive
	vim-plug
)

function help {
	echo "The update utility provides a simple interface to perform updates of programs and packages."
	usage
}

function usage {
	echo -en "\nusage: update (all"
	for t in ${targets[*]}; do
		echo -n " | $t"
	done
	echo ")"
	echo "       update help"
	exit $*
}

if [ $# -eq 0 ]; then
	>&2 echo "update: target missing"
	usage 1
fi

for t in $*; do
	case $t in
		all)
			$0 ${targets[*]}
			;;
		apt)
			apt-get update
			apt-get -f -y dist-upgrade
			apt-get autoremove
			apt-get autoclean
			;;
		prezto)
			cd "${ZDOTDIR:-$HOME}/.zprezto"
			git pull
			git submodule update --init --recursive
			;;
		nvm)
			cd "$NVM_DIR"
			git fetch origin
			git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
			source "$NVM_DIR/nvm.sh"
			;;
		npm)
			npm install -g npm@latest
			npm update -g
			;;
		cpan)
			cpan -u
			;;
		pip)
			pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
			;;
		gem)
			gem update -N
			gem cleanup
			;;
		vim-plug)
			vim +PlugUpgrade +PlugUpdate +qall
			;;
		texlive)
			sudo tlmgr update --all
			;;
		help|--help)
			help
			;;
		*)
			alt=($(which -a update))
			if [ ${#alt[@]} -gt 1 ]; then
				${alt[1]} "$@"
			else
				>&2 echo "Unknown target: $t"
				usage 1
			fi
	esac
done
