#!/bin/bash

set -euo pipefail

targets=(
	brew
	node
	perl
	prezto
	python
	ruby
	vim
)

if [ $# -eq 0 ]; then
	>&2 echo "What do you want to update?"
	listtargets
	exit 1
fi

for t in $*; do
	case $t in
		all)
			$0 ${targets[*]}
			;;
		brew)
			brew update
			brew upgrade
			brew cleanup
			brew prune
			;;
		prezto)
			cd "${ZDOTDIR:-$HOME}/.zprezto"
			git pull
			git submodule update --init --recursive
			;;
		node)
			cd "$NVM_DIR"
			git fetch origin
			git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
			source "$NVM_DIR/nvm.sh"
			npm install -g npm@latest
			npm update -g
			;;
		perl)
			cpan -u
			;;
		python)
			pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
			;;
		ruby)
			gem update
			;;
		vim)
			vim +PlugUpgrade +PlugUpdate +qall
			;;
		help)
			help
			;;
		*)
			alt=($(which update))
			if [ ${#alt} -gt 1 ]; then
				${alt[2]} "$@"
			else
				>&2 echo "Unknown target: $t"
				help 1
			fi
	esac
done

function help {
	echo "NAME"
	echo "\tupdate"
	echo
	echo "SYNOPSIS"
	echo "\tupdate target_name ..."
	echo "\tupdate help"
	echo
	echo "DESCRIPTION"
	echo "This utility provides a simple interface to perform updates of programs and packages."
	echo
	echo "TARGETS"
	listtargets
	exit $*
}

function listtargets {
	echo "\tall"
	for t in ${targets[*]}
		echo "\t$t"
}
